# Generated by Django 4.2.2 on 2023-07-03 01:31

from django.db import migrations
from django.core import serializers


def load_fixture(apps, schema_editor):
    fixture_files = [
        'menu/fixtures/menu.json'
    ]

    print("")
    for fixture_file in fixture_files:
        with open(fixture_file, 'rb') as fixture:
            print("Importando dados do arquivo '{}'".format(fixture_file))
            objects = serializers.deserialize('json', fixture, ignorenonexistent=True)
            for obj in objects:
                obj.save()

class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_alter_submenu_parent_menu'),
    ]

    operations = [
        migrations.RunPython(load_fixture),
    ]
