# Generated by Django 4.2.2 on 2023-11-05 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hobby', '0004_participante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participante',
            name='hobby',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participantes', to='hobby.hobby'),
        ),
    ]
